services:
  engine-build:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    volumes:
      - ..:/workspace

    working_dir: /workspace

    command: sleep infinity

    environment:
      VCPKG_ROOT: /home/ubuntu/vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-linux

    security_opt:
      - no-new-privileges:true
